# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170427_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='confirmed',
            field=models.NullBooleanField(default=False),
        ),
    ]
