# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170427_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.NullBooleanField(default=None)),
                ('rating', models.IntegerField(default=None)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='event',
        ),
        migrations.AddField(
            model_name='attendance',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Participant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.ManyToManyField(through='events.Attendance', to='events.Event'),
        ),
    ]
