# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170428_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
