# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170428_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(verbose_name='Ends at (local)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(verbose_name='Starts at (local)'),
        ),
    ]
