# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20170428_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='affinity_id',
            new_name='crm_id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='affinity_id',
            new_name='crm_id',
        ),
    ]
