# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20170429_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='crm_id',
            field=models.IntegerField(null=True, verbose_name='CRM id'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
