# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170423_0348'),
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('to_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Participant')),
            ],
        ),
    ]
