# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_prompt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default='unknown', max_length=32),
            preserve_default=False,
        ),
    ]
